import {
  acceptFriendRequest,
  createFriendRequest,
  createPlayer,
  createVConf,
  deleteFriend,
  deleteFriendRequest,
  deleteNotification,
  deletePlayer,
  findFriends,
  friendRequestExists,
  getFriendsList,
  getIncomingFriendRequests,
  getNewNotificationCount,
  getNotificationCount,
  getNotifications,
  getOutgoingFriendRequests,
  getPlayer,
  getVConf,
  notificationUpdateNew,
  rejectFriendRequest,
  updatePlayer,
  updateVConf
} from './src/lib/db-helper';
import prisma from './src/lib/prisma';
import { Player } from '@prisma/client';

export {
  acceptFriendRequest,
  createFriendRequest,
  createPlayer,
  createVConf,
  deleteFriend,
  deleteFriendRequest,
  deleteNotification,
  deletePlayer,
  findFriends,
  friendRequestExists,
  getFriendsList,
  getIncomingFriendRequests,
  getNewNotificationCount,
  getNotificationCount,
  getNotifications,
  getOutgoingFriendRequests,
  getPlayer,
  getVConf,
  notificationUpdateNew,
  rejectFriendRequest,
  updatePlayer,
  updateVConf,
  prisma,
  type Player
};
